server:
  port: 9527

spring:
  application:
    name: mspringcloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true


zuul:
  #ignored-services: microservicecloud-dept
  prefix: /btc
  ignored-services: "*"               #禁止以实例名访问
  routes:
    mydept.serviceId: mspringcloud-provider-dept
    mydept.path: /mydept/**

info:
  app.name: btc-mspringcloud-zuul
  company.name: www.btc.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

