server:
  port: 3344

spring:
  application:
    name:  mspringcloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/linmengl/mspringcloud-config.git    #GitHub上面的git仓库名字
#          ignore-local-ssh-settings: true

#spring:
#  application:
#    name:  mspringcloud-config
#  cloud:
#    config:
#      label: master
#      server:
#        git:
#          uri: https://github.com/linmengl/mspringcloud-config.git
#          search-paths: application
#          username:
#          password:




